version: "3.8"

services:

  server:
    hostname: server
    build:
      context: .
      dockerfile: ./build/server/Dockerfile
    command:
    - run
    - --config
    - /etc/config/config.yaml
    ports:
    - 8080:8080
    - 8081:8081
    - 8083:8083
    volumes:
    - ./configs/server:/etc/config
    restart: on-failure
    networks:
    - inference-manager

  engine:
    hostname: engine
    build:
      context: .
      dockerfile: ./build/engine/Dockerfile
    command:
    - run
    - --config
    - /etc/config/config.yaml
    ports:
    - 18080:8080
    - 18082:8082
    volumes:
    - ./configs/engine:/etc/config
    restart: on-failure
    networks:
    - inference-manager

networks:
  inference-manager:
