apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inference-manager-engine.fullname" . }}
  labels:
    {{- include "inference-manager-engine.labels" . | nindent 4 }}
data:
  config.yaml: |
    internalGrpcPort: {{ .Values.internalGrpcPort }}
    ollamaPort: {{ .Values.ollamaPort }}
    modelManagerServerWorkerServiceAddr: {{ .Values.modelManagerServerWorkerServiceAddr }}
    objectStore:
      s3:
        endpointUrl: {{ .Values.global.objectStore.s3.endpointUrl }}
        region: {{ .Values.global.objectStore.s3.region }}
        bucket: {{ .Values.global.objectStore.s3.bucket }}
