apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inference-manager-engine.fullname" . }}
  labels:
    {{- include "inference-manager-engine.labels" . | nindent 4 }}
data:
  config.yaml: |
    internalGrpcPort: {{ .Values.internalGrpcPort }}
    ollamaPort: {{ .Values.ollamaPort }}
    baseModels:
    {{- range .Values.baseModels }}
    - {{ . }}
    {{- end }}
    modelManagerServerAddr: {{ .Values.modelManagerServerAddr }}
    modelManagerInternalServerAddr: {{ .Values.modelManagerInternalServerAddr }}
    objectStore:
      s3:
        endpointUrl: {{ .Values.global.objectStore.s3.endpointUrl }}
        bucket: {{ .Values.global.objectStore.s3.bucket }}
