apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inference-manager-engine.fullname" . }}
  labels:
    {{- include "inference-manager-engine.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "inference-manager-engine.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "inference-manager-engine.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ sha256sum (toJson .Values) }}
    spec:
      containers:
      - name: inference-manager-engine
        image: "{{ .Values.image.repository }}:{{ default .Chart.Version .Values.version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - run
        - --config
        - /etc/config/config.yaml
        ports:
        - name: internal-grpc
          containerPort: {{ .Values.internalGrpcPort }}
          protocol: TCP
        - name: ollama
          containerPort: {{ .Values.ollamaPort }}
          protocol: TCP
        {{- if .Values.enableGpu }}
        resources:
          limits:
            nvidia.com/gpu: {{ .Values.gpuNumber }}
        {{- end }}
        {{- with .Values.global.awsSecret }}
        {{- if .name }}
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ .name }}
              key: {{ .accessKeyIdKey }}
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .name }}
              key: {{ .secretAccessKeyKey }}
        - name: PATH
          value: /usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        - name: LD_LIBRARY_PATH
          value: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: compute,utility
        {{- end }}
        {{- end }}
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: {{ include "inference-manager-engine.fullname" . }}
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
