apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inference-manager-engine.fullname" . }}
  labels:
    {{- include "inference-manager-engine.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "inference-manager-engine.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "inference-manager-engine.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ sha256sum (toJson .Values) }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.podTerminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.podTerminationGracePeriodSeconds }}
      {{- end }}
      serviceAccountName: {{ include "inference-manager-engine.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: inference-manager-engine
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ default .Chart.Version .Values.version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - {{ .Values.commandName }}
        - --config
        - /etc/config/config.yaml
        - --v
        - "{{ .Values.logLevel }}"
        ports:
        {{- if eq .Values.commandName "run_monolithic" }}
        - name: llm
          containerPort: {{ .Values.llmPort }}
          protocol: TCP
        {{- end }}
        - name: health
          containerPort: {{ .Values.healthPort }}
          protocol: TCP
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- if eq .Values.commandName "run_monolithic" }}
        {{- with .Values.global.awsSecret }}
        {{- if .name }}
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ .name }}
              key: {{ .accessKeyIdKey }}
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .name }}
              key: {{ .secretAccessKeyKey }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- with .Values.global.worker.registrationKeySecret }}
        {{- if .name }}
        - name: LLMO_CLUSTER_REGISTRATION_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .name }}
              key: {{ .key }}
        {{- end }}
        {{- end }}
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
        {{- if eq .Values.commandName "run_monolithic" }}
        - name: store
          mountPath: /tmp
        - name: store
          mountPath: /.ollama
        {{- end }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "inference-manager-engine.fullname" . }}
      {{- if eq .Values.commandName "run_monolithic" }}
      - name: store
      {{- if .Values.persistentVolume.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistentVolume.existingClaim | default (include "inference-manager-engine.fullname" .) }}
      {{- else }}
        emptyDir:
      {{- end }}
      {{- end }}
