{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "inference-manager-engine.serviceAccountName" . }}
  labels:
    {{- include "inference-manager-engine.labels" . | nindent 4 }}
{{- end -}}
