{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "inference-manager-dispatcher.serviceAccountName" . }}
  labels:
    {{- include "inference-manager-dispatcher.labels" . | nindent 4 }}
{{- end -}}
