{{- if eq .Values.commandName "run_monolithic" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "inference-manager-engine.fullname" . }}-llm
  labels:
    {{- include "inference-manager-engine.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.llmPort }}
      targetPort: llm
      protocol: TCP
      name: llm
  selector:
    {{- include "inference-manager-engine.selectorLabels" . | nindent 4 }}
{{- end }}
