apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inference-manager-server.fullname" . }}
  labels:
    {{- include "inference-manager-server.labels" . | nindent 4 }}
data:
  config.yaml: |
    grpcPort: {{ .Values.grpcPort }}
    httpPort: {{ .Values.httpPort }}
    workerServiceGrpcPort: {{ .Values.workerServiceGrpcPort }}
    monitoringPort: {{ .Values.monitoringPort }}
    modelManagerServerAddr: {{ .Values.modelManagerServerAddr }}
    auth:
      enable: {{ .Values.global.auth.enable }}
      rbacInternalServerAddr: {{ .Values.global.auth.rbacInternalServerAddr }}
