apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inference-manager-server.fullname" . }}
  labels:
    {{- include "inference-manager-server.labels" . | nindent 4 }}
data:
  config.yaml: |
    grpcPort: {{ .Values.grpcPort }}
    httpPort: {{ .Values.httpPort }}
    monitoringPort: {{ .Values.monitoringPort }}
    modelManagerServerAddr: {{ .Values.modelManagerServerAddr }}
    inferenceManagerEngine:
      ollamaPort: {{ .Values.inferenceManagerEngine.ollamaPort }}
      internalGrpcPort: {{ .Values.inferenceManagerEngine.internalGrpcPort }}
      namespace: {{ .Values.inferenceManagerEngine.namespace | default .Release.Namespace | quote }}
      labelKey: {{ .Values.inferenceManagerEngine.labelKey }}
      labelValue: {{ .Values.inferenceManagerEngine.labelValue }}
