apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inference-manager-server.fullname" . }}
  labels:
    {{- include "inference-manager-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "inference-manager-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "inference-manager-server.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ sha256sum (toJson .Values) }}
    spec:
      serviceAccountName: {{ include "inference-manager-server.serviceAccountName" . }}
      containers:
      - name: inference-manager-server
        image: "{{ .Values.image.repository }}:{{ default .Chart.Version .Values.image.version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - run
        - --config
        - /etc/config/config.yaml
        ports:
        - name: http
          containerPort: {{ .Values.httpPort }}
          protocol: TCP
        - name: grpc
          containerPort: {{ .Values.grpcPort }}
          protocol: TCP
        - name: ws-grpc
          containerPort: {{ .Values.workerServiceGrpcPort }}
          protocol: TCP
        - name: monitoring
          containerPort: {{ .Values.monitoringPort }}
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
        {{- if .Values.workerServiceTls.enable }}
        - name: tls
          mountPath: /var/run/tls
          readOnly: true
        {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "inference-manager-server.fullname" . }}
      {{- if .Values.workerServiceTls.enable }}
      - name: tls
        secret:
          secretName: {{ .Values.workerServiceTls.secretName }}
      {{- end }}
