internalGrpcPort: 8082
ollamaPort: 8080
objectStore:
inferenceManagerServerWorkerServiceAddr: server:8082
modelManagerServerWorkerServiceAddr:

debug:
  standalone: true
  baseModels:
  - google/gemma-2b
