global:
  ingress:
    ingressClassName:

  auth:
    enable:
    rbacInternalServerAddr:

httpPort: 8080
grpcPort: 8081
monitoringPort: 8083

inferenceManagerEngine:
  ollamaPort: 8080
  internalGrpcPort: 8082
  labelKey: app.kubernetes.io/name
  labelValue: inference-manager-engine

# The following default values work if model manager server runs in the same namespace.
modelManagerServerAddr: model-manager-server-grpc:8081

replicaCount: 1
image:
  repository: public.ecr.aws/v8n3t7y5/llm-operator/inference-manager-server
  pullPolicy: IfNotPresent
  version:

enableServiceMonitor: false

service:
  annotations:

serviceAccount:
  create: true
