global:
  ingress:
    ingressClassName:
    annotations:
    tls:
      hosts:
      secretName:

  auth:
    enable:
    rbacInternalServerAddr:

  workerServiceGrpcService:
    annotations:

  workerServiceIngress:
    create: false
    ingressClassName:
    annotations:
    tls:
      hosts:
      secretName:

httpPort: 8080
grpcPort: 8081
workerServiceGrpcPort: 8082
monitoringPort: 8083

workerServiceGrpcService:
  type: ClusterIP
  port: 8082
  nodePort:
  annotations:
  loadBalancerSourceRanges:

workerServiceTls:
  enable: false
  secretName:

# The following default values work if model manager server runs in the same namespace.
modelManagerServerAddr: model-manager-server-grpc:8081

vectorStoreManagerServerAddr: vector-store-manager-server-grpc:8081
vectorStoreManagerInternalServerAddr: vector-store-manager-server-internal-grpc:8083

replicaCount: 1
image:
  repository: public.ecr.aws/cloudnatix/llm-operator/inference-manager-server
  pullPolicy: IfNotPresent

podAnnotations:
nodeSelector:
affinity:
tolerations:

version:

enableServiceMonitor: false
enablePrometheusRule: false

service:
  annotations:

serviceAccount:
  create: true

resources:
  requests:
    cpu: "250m"
    memory: "500Mi"
  limits:
    cpu: "250m"

livenessProbe:
  httpGet:
    path: /healthz
    port: http
    scheme: HTTP
  initialDelaySeconds: 3
  failureThreshold: 5
  timeoutSeconds: 3

podSecurityContext:
  fsGroup: 2000
securityContext:
  readOnlyRootFilesystem: true
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  runAsUser: 1000
