global:
  ingress:
    ingressClassName:

httpPort: 8080
grpcPort: 8081
monitoringPort: 8083

# The following default values work if ollama server runs in the same namespace.
ollamaServerAddr: llm-operator-inference-manager-engine-ollama:8080

replicaCount: 1
image:
  repository: public.ecr.aws/v8n3t7y5/llm-operator/inference-manager-server
  pullPolicy: IfNotPresent
  version:

enableServiceMonitor: false
