global:
  ingress:
    ingressClassName:
    annotations:
    tls:
      hosts:
      secretName:

  auth:
    enable:
    rbacInternalServerAddr:

  workerServiceGrpcService:
    annotations:

  workerServiceIngress:
    create: false
    ingressClassName:
    annotations:
    tls:
      hosts:
      secretName:

httpPort: 8080
grpcPort: 8081
workerServiceGrpcPort: 8082
monitoringPort: 8083

# The following default values work if model manager server runs in the same namespace.
modelManagerServerAddr: model-manager-server-grpc:8081

replicaCount: 1
image:
  repository: public.ecr.aws/v8n3t7y5/llm-operator/inference-manager-server
  pullPolicy: IfNotPresent
  version:

enableServiceMonitor: false

service:
  annotations:

serviceAccount:
  create: true
