global:
  objectStore:
    s3:
      endpointUrl:
      region:
      bucket:

  awsSecret:
    name:
    accessKeyIdKey:
    secretAccessKeyKey:

  ingress:
    ingressClassName:

internalGrpcPort: 8081
ollamaPort: 8080

baseModels:

modelManagerServerAddr:
modelManagerInternalServerAddr:

replicaCount: 1
image:
  repository: public.ecr.aws/v8n3t7y5/llm-operator/inference-manager-engine
  pullPolicy: IfNotPresent

ingress:
  ingressClassName:

version:
