internalGrpcPort: 8081
ollamaPort: 8080

modelManagerServerAddr:
modelManagerInternalServerAddr:

objectStore:
  s3:
    endpointUrl:
    bucket:

awsSecret:
  name:
  accessKeyIdKey:
  secretAccessKeyKey:

replicaCount: 1
image:
  repository: public.ecr.aws/v8n3t7y5/llm-operator/inference-manager
  pullPolicy: IfNotPresent

ingress:
  ingressClassName:

version:
