global:
  objectStore:
    s3:
      endpointUrl:
      region:
      bucket:

  awsSecret:
    name:
    accessKeyIdKey:
    secretAccessKeyKey:

  ingress:
    ingressClassName:

internalGrpcPort: 8081
ollamaPort: 8080

modelSyncInterval: 1m

# The following default values work if model-manager-server runs in the same namespace.
modelManagerServerAddr: llm-operator-model-manager-server-grpc:8081
modelManagerInternalServerAddr: llm-operator-model-manager-server-internal-grpc:8082

replicaCount: 1
image:
  repository: public.ecr.aws/v8n3t7y5/llm-operator/inference-manager-engine
  pullPolicy: IfNotPresent

ingress:
  ingressClassName:

version:
